config/routes.rb
Rails.application.routes.draw do
  get "/" => "users#home"
  get "/home" => "users#home"
  get "/my_posts" => "posts#my_posts"
  get "/login_form" => "users#login_form"
  post "/login" => "users#login"
  get "/logout" => "users#logout"
  get "/new_comment/:user_id/:post_id" => "comments#new"
  get "/profile_posts/:id" => "posts#profile_posts"
  get "/my_comments" => "comments#my_comments"

  resources :users do
    resources :posts
  end
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :username, uniqueness: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  def current_user
    puts "******* current_user *******"
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
    puts "@current_user: #{@current_user.inspect}"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  def my_comments
    puts "**** my_posts ****"
    @my_comments = @current_user.comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    puts "**** new comments *****"
    puts "params: #{params.inspect}"
    @comment = Comment.new
    @post = Post.find(params[:post_id])
    puts "@post: #{@post.inspect}"
  end

  # GET /comments/1/edit
  def edit
    puts "**** edit comments *****"
    @post = Comment.find(params[:post_id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_path(@comment), notice: 'Comment was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def my_posts
    puts "**** my_posts ****"
    @my_posts = @current_user.posts
  end

  def profile_posts
    puts "**** profile_posts ****"
    @user = User.find(params[:id])
    @current_posts = @user.posts
  end

  # GET /posts # GET /posts.json
  def index
    @posts = Post.all
    @comments = Comment.all
  end

  # GET /posts/1 # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    puts "**** new post ****"
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    puts "**** edit post ****"
  end

  # POST /posts
  # POST /posts.json
  def create
    puts "**** create post ****"
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to my_posts_path, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
    puts "@current_user: #{@current_user.inspect}"
    puts "@post: #{@post.inspect}"
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to user_posts_path(@current_user[:id]), notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1 # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_posts_path(@current_user[:id]), notice: 'Post was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @current_user[:id]
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      # params.fetch(:post, {})
      params.require(:post).permit(:user_id, :title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def home
    puts "**** home ****"
  end

  def login_form
    puts "**** login_form ****"
  end

  def login
    puts "\n******* login *******"
    # puts "params: #{params.inspect}" # unapproved params
    ok_params = login_params
    @user = User.where(username: ok_params[:username]).first
    puts "@user: #{@user.inspect}"
    if @user
      if @user.password == ok_params[:password]
        session[:user_id] = @user[:id]
        puts "session[:user_id]: #{session[:user_id].inspect}"
        current_user
        redirect_to :home
      else
        redirect_to "/login_form", notice: 'Your password was incorrect.  Please try again'
      end
    else
       redirect_to "/login_form", notice: 'Your username was incorrect.  Please try again'
    end
  end

  def logout
    puts "**** logout ****"
    session[:user_id] = nil
    redirect_to :home, notice: "See you for your next vacation!"
  end

  # GET /users /users.json
  def index
    puts "**** index ****"
    @users = User.all
  end

  # GET /users/1   # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to home_path(@user), notice: 'New user profile was successfully created. Please log in.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User profile was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    session[:user_id] = nil
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def login_params
      puts "******* login_params *******"
      params.permit(:username, :password)
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      puts "**** user_params ****"
      params.require(:user).permit(:firstname, :lastname, :email, :username, :password)
      # params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    Content <br> <%= form.text_area :content, :id => "postStyleTwo" %><br>
    <%= form.hidden_field :user_id, value: @current_user[:id] %>
    <%= form.hidden_field :post_id, value: @post[:id] %>
    <%= form.submit "SUBMIT", :class => "buttonStyle" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="homePage">
  <h2>Edit or Update your Comment</h2>
  <%= render 'form', comment: @comment %>
  <%= link_to 'Back', comments_path %>
</div>

app/views/comments/index.html.erb
<!--not using-->

app/views/comments/my_comments.html.erb
<div class="homePage">
  <h2>My Comments</h2>
  <div class="postInfo">
    <% @my_comments.each do |comment| %>
      <p><%= comment[:content] %></p>
      <p class="timeStamp"> Timestamp: <%= comment[:created_at] %></p>
      <span> edit |</span>
      <%= link_to 'delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => "backButtons" %>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="homePage">
  <h2>Write a Comment</h2>
  <%= render 'form', comment: @comment %>
  <%= link_to 'Back', user_posts_path(:user_id), :class => "backButtons" %>
</div>

app/views/comments/show.html.erb
<div class="homePage">
  <% user = User.find(@comment[:user_id]) %>
  <h3><%= @comment[:content] %></h3>
  <p class="timeStamp"> Timestamp: <%= @comment[:created_at] %></p>
  <%= link_to 'view all tips', user_posts_path(:user_id), :class => "backButtons" %> |
  <span> edit comment | </span>
  <%= link_to 'delete comment', comment_path(@comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => "backButtons" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MP_Rails_Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
  </head>
  <body>
    <header>
      <% if @current_user %>
        <h1>Life's a Beach: Vacation Tips</h1>
        <%= render :partial => "/users/menu" %>
      <% else %>
          <h1>Life's a Beach: Vacation Tips</h1>
        <nav>
          <%= link_to "Home", "/home" %> |
          <%= link_to "Login", "/login_form" %> |
          <%= link_to "Signup", new_user_path %> |
          <%= link_to "View All Posts", user_posts_path(:user_id) %>
        </nav>
      <% end %>
    </header>
    <div id="yield" class="section">
      <%= yield %>
    </div>
    <footer>
      <% if notice %>
          <p id="notice"><%= notice %></p>
          <hr>
      <% end %>
      <p>&copy; 2017 Megan Penn</p>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, url: user_posts_path(@current_user[:id]), local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="homePage">
  <h2>Edit or Update Your Post</h2>
  <%= form_with(model: @post, url: user_post_path(@current_user[:id], @post), local: true) do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="actions">
      Subject <br> <%= form.text_field :title, :id => "postStyleOne" %><br> <br>
      Content <br> <%= form.text_area :content, :id => "postStyleTwo" %><br>
      <%= form.hidden_field :user_id, value: @current_user[:id] %>
      <%= form.submit "SUBMIT", :class => "buttonStyle" %>
    </div>
  <% end %><br>
  <%= link_to 'Back', user_posts_path, :class => "backButtons" %>
</div>

app/views/posts/index.html.erb
<div class="homePage">
  <h2>All Tips on Life's a Beach</h2>

  <div class="postInfo">
    <% @posts.each do |post| %>
      <% user = User.find(post[:user_id]) %>
      <h3><%= post[:title] %> by: <%= link_to user[:firstname] + " " + user[:lastname], user_path(user), :class => "userNames" %></h3>
      <p><%= post[:content] %></p>
      <p class="timeStamp"> Timestamp: <%= post[:created_at] %></p>
      <% if @current_user %>
        <%= link_to 'Add Comment', '/new_comment/' + @current_user[:id].to_s + '/' + post[:id].to_s, :class => "backButtons" %>
      <% end %>
      <% @comments.each do |comment| %>
        <% if post[:id] == comment[:post_id] %>
          <% commentUser = User.find(comment[:user_id]) %>
          <div class="commentInfo">
            <p><%= link_to commentUser[:firstname] + " " + commentUser[:lastname], user_path(commentUser), :class => "userNames" %> says: <%= comment[:content] %></p>
            <p class="timeStamp">Timestamp: <%= comment[:created_at] %></p>
            <% if @current_user[:id] == comment[:user_id] %>
              <%= link_to 'Edit', edit_comment_path(comment), :class => "backButtons" %> |
              <%= link_to 'delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => "backButtons" %>
            <% elsif @current_user[:id] == post[:user_id] %>
              <%= link_to 'delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => "backButtons" %>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <hr>
    <% end %>
  </div>
</div>

app/views/posts/my_posts.html.erb
<div class="homePage">
  <h2>My Posts</h2>
  <div class="postInfo">
    <% @my_posts.each do |post| %>
      <h3><%= post[:title] %></h3>
      <p><%= post[:content] %></p>
      <p class="timeStamp"> Timestamp: <%= post[:created_at] %></p>
      <%= link_to 'Edit', edit_user_post_path(@current_user[:id], post), :class => "backButtons" %> |
      <%= link_to 'Delete', user_post_path(@current_user[:id], post), method: :delete, data: { confirm: 'Are you sure?' }, :class => "backButtons" %>
    <% end %>
  </div>
  <hr>
  <%= link_to 'my comments', my_comments_path, :class => "backButtons" %>
</div>

app/views/posts/new.html.erb
<div class="homePage">
<h2>Create a New Post</h2>
<%= form_with(model: @post, url: user_posts_path(@current_user[:id]), local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    Subject <br> <%= form.text_field :title, :id => "postStyleOne" %><br> <br>
    Content <br> <%= form.text_area :content, :id => "postStyleTwo" %><br>
    <%= form.hidden_field :user_id, value: @current_user[:id] %>
    <%= form.submit "SUBMIT", :class => "buttonStyle" %>
  </div>
<% end %>
</div>

app/views/posts/profile_posts.html.erb
<div class="homePage">
  <h2><%= @user[:firstname] + " " + @user[:lastname] %>'s Tips</h2>
  <h3>Username: <%= @user[:username] %></h3>
  <div class="postInfo">
    <% @current_posts.each do |post| %>
      <h3><%= post[:title] %></h3>
      <p><%= post[:content] %></p>
      <p class="timeStamp"> Timestamp: <%= post[:created_at] %></p>
    <% end %>
  </div>
  <%= link_to 'View my Profile', user_path(@user), :class => "backButtons" %>
</div>

app/views/posts/show.html.erb
<!--not using-->

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    First Name: <%= form.text_field :firstname %><br>
    Last Name: <%= form.text_field :lastname %><br>
    Username: <%= form.text_field :username %><br>
    Password: <%= form.text_field :password %><br>
    Email: <%= form.text_field :email %><br>
  <div class="actions">
    <%= form.submit "ENTER", :class => "buttonStyle" %>
  </div>
<% end %>

app/views/users/_menu.html.erb
<nav>
  <ul>
    <li><%= link_to "Home", "/home" %> |</li>
    <li><%= link_to "New Post", new_user_post_path(@current_user) %> |</li>
    <li><%= link_to "My Posts", my_posts_path %> |</li>
    <li><%= link_to "View All Posts", user_posts_path(:user_id) %> |</li>
    <li><%= link_to "View All Users", users_path %> |</li>
    <li><%= link_to "Edit Profile", edit_user_path(@current_user) %> |</li>
    <li><%= link_to "Delete Profile", @current_user, method: :delete, data: { confirm: '*** Are you sure you want to delete your account? This action cannot be undone. ***' } %> |</li>
    <li><%= link_to "Logout", "/logout" %>
  </ul>
</nav>

app/views/users/edit.html.erb
<div class="homePage">
  <h2>Edit Your Account</h2>
  <%= render 'form', user: @user %>
  <%= link_to 'Show Profile', @user, :class => "backButtons" %> |
  <%= link_to 'Go Back', users_path, :class => "backButtons" %>
</div>

app/views/users/home.html.erb
<div class="homePage">
  <% puts "@current_user: #{@current_user.inspect}" %>
  <% if @current_user %>
    <h2>Welcome back! Let's start planning your next vacation</h2>
  <% end %>
  <%= image_tag("paws_vacation.jpg", :alt => "Pup on Vacation") %>
  <p>A place to share your favorite travel spots, and tips to visit
    and eat.</p>
  <h2 class="quotes">"It's bad manners to keep a vacation waiting."</h2>
</div>

app/views/users/index.html.erb
<div class="homePage">
  <h2>Members Looking for a Vacation</h2>
  <% @users.each do |user| %>
    <h3>&raquo; <%= link_to user[:firstname] + " " + user[:lastname], user_path(user), :class => "userNames" %></h3>
  <% end %>
</div>

app/views/users/login_form.html.erb
<div class="homePage">
  <h2>Member Login</h2>
  <%= form_with url: '/login', method: 'post', local: true do |form| %>
      Username: <%= form.text_field :username, value: "mtp" %><br>
      Password: <%= form.text_field :password, value: "mtp123" %><br>
      <%= form.submit "ENTER", :class => "buttonStyle" %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="homePage">
  <h2>Sign Up</h2>
  <%= render 'form', user: @user %>
  <br>
  <%= link_to 'Go Back', users_path, :class => "backButtons" %>
</div>

app/views/users/show.html.erb
<div class="homePage">
  <%= image_tag("sunglasses.png", :alt => "User Avatar") %>
  <h2><%= @user[:firstname] + " " + @user[:lastname] %></h2>
  <h3>Username: <%= @user[:username] %></h3>
  <h3>Member Since: <%= @user[:created_at] %></h3>
  <%= link_to 'View my Tips', '/profile_posts/' + @user[:id].to_s, :class => "backButtons" %> |
  <%= link_to 'Go Back', users_path, :class => "backButtons" %>
</div>